### PR TITLE
Comma and pointer tests

### PR DESCRIPTION
**Pull request by johncarl81**
Testing comma assignment  and a pointer reference test

### CODE REVIEW

**Comment by jmciver** [comment]
The following work for me: is1_36, is1_37, and is2_22.

I think there is an issue with is4_11. The statment "p[] = a;" is attempting to dereference a pointer that has not been set. My thinking is this is attempting to write the value of "a" to address 0x00000000 as SPIM initializes memory to zero for us.

A more useful test might be to set p using the following:
p = &a;

And then the following should retrieve the value via pointer dereference:
p[];

**Comment by johncarl81** [comment]
Yeah, not sure that's a valid test anymore... I was trying to test something similar to `*p = 1`, but we don't allow for setting pointers to constants.... at least I don't think we do.

**Comment by jmciver** [comment]
P = P => P

Could initialize p to 0x10008000 via TLC header that would do the trick.

**Comment by jmciver** [comment]
Works for me.

**Comment by theguruat12** [comment]
Pointer tests work fine for me, comma not so much but that's due to my lack of implementation

**Pull request merged**
