### PR TITLE
Added John Ericksen's tests

### PR DESCRIPTION
**Pull request by johncarl81**
Combined and added my tests to the testing set.  Noteworthy additions are:
* Array indexing
* Unary operations
* Boolean short circuiting
* Control statements
* Pointer handling. 

For organization I renamed files based on ISEQ number: `is<ISEQ#>_<TEST#>.loboc`
I liked the formatting from @tylersheltonnn's PR - one case per line and consistent spacing - so I extended it across the testing set.  Here's what it looks like:
```
// ISEQ1: Test negate operation
//tlc type: run
//tlc case: 1=-1
//tlc case: -1=1
//tlc case: -1000=1000
//tlc case: 2=-2
//tlc case: -2=2
//tlc case: 0xffffffff=1
signed a;
-a;
```

### CODE REVIEW

**Review by tylersheltonnn — APPROVED** [review]
This looks good. I am sorry I did not rename the files. I did not understand the naming convention before. Now I do.

**Comment by johncarl81** [comment]
No problem.  I definitely wasn't clear.

**Review by tylersheltonnn — APPROVED** [review]
I can't see anything wrong with these... but I am not at a place to test all of them yet.

**Comment by brendan-donohoe** [comment]
Just wanted to report that all of your tests passed on my end, John.  The only thing I noticed is that, although I ended up including it in my implementation as well, I don't think the unary & operator is required for ISEQ 4 in is4_10.loboc (which seems... very weird in hindsight).

**Comment by johncarl81** [comment]
Thanks for the feedback @brendan-donohoe.  Yeah, I realized that the `&` operator wasn't called out in the spec, but I figured what use would the pointer `[]` operator be without the corresponding operator to create a pointer?

**Pull request merged**
