### PR TITLE
Adding regression set created by John K. McIver III

### PR DESCRIPTION
**Pull request by jmciver**
The originating repository resides at:
https://bitbucket.org/jkmciver/cs554_spring2018_spike5_regressions

### CODE REVIEW

**Comment by brendan-donohoe** [comment]
Can finally confirm that tests for ISEQ1 to ISEQ3 work for me.  Still need to do a bit more reworking for the ISEQ4 tests (all reworking done has, so far, been due to oversights on my part, and not errors in the tests).

**Comment by jmciver** [comment]
I am going to recommend that we do not merge my branch at this point. I have added some additional tests to my repository and will continue to do so over the next day.

**Comment by johncarl81** [comment]
I'm working through these tests like @brendan-donohoe is... this was good, it exposed a couple of incomplete spots for me.

We'll keep this open until you say the word @jmciver

**Comment by brendan-donohoe** [comment]
Alright, almost there.  The ISEQ4 tests have been fantastic, by the way - there's just one question I have so far.

In is4_pointer_array_unsigned.loboc (and the signed variant as well) we have a statement like the following:

dp[][i++]--;

Does C define the order in which the post-increment and post-decrement occur relative to one another in this particular case?

**Comment by johncarl81** [comment]
@brendan-donohoe, would order matter here?  Shouldn't `dp[][i++]--` behave the same as `dp[][i]--`?

**Comment by brendan-donohoe** [comment]
You're absolutely right.  Sorry about that!

**Comment by johncarl81** [comment]
No worries, just making sure I'm thinking straight too!

**Comment by brendan-donohoe** [comment]
Okay, finished with all of the tests!

In case other folks are having any weird trouble, the main problems I had at the end were with is4_pointer3 is2_array2x3x4_signed, each of which had a segment where the pointer is incremented four times to increment by the value of a word.  In my implementation (which is certainly not the only approach possible), I had each individual increment step by the size of the type of whatever the pointer was pointing to.  So, I stripped the four pointer increments down to one in each of those cases, and then the tests ended up passing for me.  If others are stuck and took a similar approach for pointer incrementing/decrementing, that should work.

But seriously, these tests have been awesome, and incredibly helpful in dejankifying my compiler.  Thank you so much for sharing them!

**Comment by johncarl81** [comment]
@jmciver I'm prepping to merge this in and it looks like adding the rest of your tests would be trivial... could you add the rest of your tests from your other repo?

**Comment by johncarl81** [comment]
Gasp, was that a force push @jmciver ?

**Comment by jmciver** [comment]
Yes, yes it was!

**Comment by jmciver** [comment]
Did I screw something up for you?

**Comment by johncarl81** [comment]
Nah.  I appreciate the update!

**Comment by jmciver** [comment]
I am assuming that everyone is done at this point, but merging for posterity is good.

**Pull request merged**
